name: Flutter iOS Release

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.44.1

      - name: Verify Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS Release
        run: flutter build ipa --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Upload IPA to Firebase Distribution
        run: |
          firebase appdistribution:distribute \
          build/ios/ipa/*.ipa \
          --app ${{ secrets.FIREBASE_IOS_APP_ID }} \
          --groups Zappkode Testers \
          --release-notes "New iOS Testing Build" \
          --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/ipa