name: Flutter iOS Release

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.44.1

      - name: Verify Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS Release
        run: flutter build ios --release --no-codesign

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/iphoneos
